### ISSUE TITLE
viewport and bounds don't return the same values

### ISSUE THREAD

**Issue by rgazelot** [mapbox/geo-viewport#23]
Hello, I'm working with this library in order to compose a big image with a matrix of 3x4 images. I compute precisely the bounds of each images to retrieved them through the Static API. I am not be able to correctly connect the dots between each images, because I think that the zoom level I have from `viewport()` is slightly lower than expected. I also found that reverse the viewport using `bound()` doesn't give my my initial bounds. This is a problem when you try to be extremely precise.

```js
const viewport = geoViewport.viewport([
    -5.715601797359881,
    51.267265845221885,
    -2.2190913285227603,
    53.69793118651373
      ], [1169, 1240], undefined, undefined, 512, true)

// { center: [-3.9673465629413203, 52.48259851586781], zoom: 7.770670445470639 }

const bounds = geoViewport.bounds([viewport.center[0], viewport.center[1]], viewport.zoom, [1169, 1240], 512)

// [-5.8493142602338875, 51.250005339825485, -2.0853788656487575, 53.681598862577374]
```
I played with the mapbox-gl-js in a [JSFiddle here](https://jsfiddle.net/gupt3n9v/) I found that the zoom level is more `7.816474199832816`. 

Did I missed something?

**Comment by tyhupo** [comment]
I have some problems with zoom level too but i am only using viewport. There is maybe an issue with this method.

**Comment by tsuz** [comment]
@rgazelot 

![スクリーンショット 0032-02-20 13 39 26](https://user-images.githubusercontent.com/6927131/74901528-72184c80-53e6-11ea-983e-f3a9c6ea4147.png)

[This test case](https://github.com/mapbox/geo-viewport/commit/be310b0bc9bcf94871c9fea2ab2e7979a67a3bdd) shows the bounds do not return the same values. I have not found the root cause but it may have to do with [this dependency](https://github.com/mapbox/sphericalmercator)

It seems like using your initial bounds, 
```
[  
   -5.715601797359881,
    51.267265845221885,
    -2.2190913285227603,
    53.69793118651373
]
```
A - your original SW
B - your original NE
C - returned SW
D - returned NE

![response](https://user-images.githubusercontent.com/6927131/74901131-39c43e80-53e5-11ea-82cc-b3a7868c4416.jpeg)

You can see from the bounds set, [the black rectangle is not covering the image](https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/geojson(%7B%0A%20%20%20%20%22type%22%3A%20%22FeatureCollection%22%2C%0A%20%20%20%20%22features%22%3A%20%5B%7B%0A%20%20%20%20%20%20%22type%22%3A%20%22Feature%22%2C%0A%20%20%20%20%20%20%20%20%22geometry%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22LineString%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22coordinates%22%3A%20%5B%0A%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-5.715601797359881%2C%0A%20%20%20%2051.267265845221885%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-5.715601797359881%2C%0A%20%20%20%2053.69793118651373%5D%2C%0A%5B%20%20%20%20-2.2190913285227603%2C%0A%20%20%20%2053.69793118651373%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20-2.2190913285227603%2C%0A%20%20%20%2051.267265845221885%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-5.715601797359881%2C%0A%20%20%20%2051.267265845221885%5D%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%22properties%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22line-color%22%3A%22blue%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%5D%0A%7D)/-3.9673465629413203,52.48259851586781,7.770670445470639,0,0/1169x1240@2x?access_token=pk.eyJ1IjoidGFrdXRvc3V6dWtpbWFwYm94IiwiYSI6ImNrMjJlMXplcTE4a2czY3F3MWkxZHN4cWkifQ.CRcFM34KAOiPKIbscodOqA).

![スクリーンショット 0032-02-20 13 37 51](https://user-images.githubusercontent.com/6927131/74901445-3b423680-53e6-11ea-9f52-4b77ce57fdf1.png)

[This image](https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/geojson(%7B%0A%20%20%20%20%22type%22%3A%20%22FeatureCollection%22%2C%0A%20%20%20%20%22features%22%3A%20%5B%7B%0A%20%20%20%20%20%20%22type%22%3A%20%22Feature%22%2C%0A%20%20%20%20%20%20%20%20%22geometry%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22LineString%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22coordinates%22%3A%20%5B%0A%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-5.715601797359881%2C%0A%20%20%20%2051.267265845221885%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-5.715601797359881%2C%0A%20%20%20%2053.69793118651373%5D%2C%0A%5B%20%20%20%20-2.2190913285227603%2C%0A%20%20%20%2053.69793118651373%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20-2.2190913285227603%2C%0A%20%20%20%2051.267265845221885%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20-5.715601797359881%2C%0A%20%20%20%2051.267265845221885%5D%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%22properties%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22line-color%22%3A%22blue%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%22type%22%3A%20%22Feature%22%2C%0A%20%20%20%20%20%20%20%20%22geometry%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22LineString%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22coordinates%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B-5.8493142602338875%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%2C%2051.250005339825485%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B-5.8493142602338875%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%2C53.681598862577374%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%5B%20%20-2.0853788656487575%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%2C%20%2053.681598862577374%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B%20%20%20-2.0853788656487575%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%2C%20%2051.250005339825485%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B-5.8493142602338875%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%2C%2051.250005339825485%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%22properties%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22line-color%22%3A%22red%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%5D%0A%7D)/-3.9673465629413203,52.48259851586781,7.770670445470639,0,0/1169x1240@2x?access_token=pk.eyJ1IjoidGFrdXRvc3V6dWtpbWFwYm94IiwiYSI6ImNrMjJlMXplcTE4a2czY3F3MWkxZHN4cWkifQ.CRcFM34KAOiPKIbscodOqA) shows the bounds that you want is not covering the image exactly the way it should.



<details>
<summary>The GeoJSON I used are here</summary>

```
{
  "type": "FeatureCollection",
  "features": [{
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [-5.715601797359881,
            51.267265845221885
          ],
          [-5.715601797359881,
            53.69793118651373
          ],
          [-2.2190913285227603,
            53.69793118651373
          ],
          [-2.2190913285227603,
            51.267265845221885
          ],
          [-5.715601797359881,
            51.267265845221885
          ]

        ]
      },
      "properties": {
        "line-color": "blue"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [-5.8493142602338875, 51.250005339825485],
          [-5.8493142602338875, 53.681598862577374],
          [-2.0853788656487575, 53.681598862577374],
          [-2.0853788656487575, 51.250005339825485],
          [-5.8493142602338875, 51.250005339825485]
        ]
      },
      "properties": {
        "line-color": "red"
      }
    }
  ]
}
```
</details>

**Comment by rgazelot** [comment]
@tsuz Thanks for taking the time to work on this. Your image shows exactly what I'm facing! The bounds used internally by the `viewport` method are not mine, which results to a wrong `zoom` level computation which will expand a little bit the area visible. 

This issue seems to come from a certain initial zoom level. I worked with images using initials bounds from levels 15 or 16 and my images are perfectly aligned. This seems to begin to appear at only a level 10 or 12 something. I'll take the time to test multiple case to see if this is real and see if this can help.

**Comment by tsuz** [comment]
@rgazelot 

By design, here is the explanation of what you're trying to do will not return the result as expected.

![75790105-b259c200-5d38-11ea-9663-9ed580f68c03](https://user-images.githubusercontent.com/6927131/75847027-6898d680-5e21-11ea-9b3b-3366a0f53fd0.png)

**Comment by rgazelot** [comment]
@tsuz This make sense! I understand why this doesn't work as expected. Thanks a lot for your time and the help of the team. Best regards.
